### ISSUE TITLE
Set I2C Protocol between Pi & ESP32

### ISSUE THREAD

**Issue by bgoodwine** [bgoodwine/SeniorDesign#11]
### Protocol Draft 1
Pi initial requests: 
* `0:` = request for general checkin
* `1:[IMU data]` = IMU data that the ESP32 should either confirm or alert mismatching data 
* `2:[num_bytes]` = transmit message via SDR 
* `3:sensor_id` = restart sensor corresponding to `sensor_id`
* `4:sensor_id` = shutdown sensor corresponding to `sensor_id`
* `0:2` = start relay of available SDR message (sent after receiving `0:2` from ESP32)
* `0:3` = start relay of solar panel efficiency report (sent after receiving `0:3` from ESP32)
 
ESP32 response to general checkin: 
* `0:0` = not tumbling
* `0:1` = tumbling alert
* `0:2:[num_bytes]` = message from SDR waiting to be relayed 
* `0:3:[num_bytes]` = solar panel efficiency report available for relay 

ESP32 response to IMU data: 
* `1:0` = IMU data is good
* `1:1` = IMU data does not match
* `1:report:[solar panel report]` = solar panel efficiency report 
* `2:num_bytes` = number of bytes in message received from the SDR, which the ESP32 will next relay to the Pi
* `2:[message]` = message relayed to Pi, will only be `num_bytes` long

ESP32 data relay:
* `2:[message]` - SDR message to relay, repeat until `num_bytes` has been sent (-2 for each sent message)
* `3:[report]` - solar panel efficiency report to relay, repeat until `num_bytes` has been sent (-2 for each sent message)

_Originally posted by @bgoodwine in https://github.com/bgoodwine/SeniorDesign/issues/2#issuecomment-1438757839_

**Comment by bgoodwine** [comment]
### TODO
- [ ] Change structure of `i2c_esp32.py` to be functions for import in other programs
- [ ] Add functions for each type of message to send (`checkin()`, `send_to_sdr(message)`, `send_imu_update(imu_data)`, etc.)
- [ ] Send opcode and `num_bytes` for all messages
- [ ] Repeat messages in 32-byte chunks until whole message sent
- [ ] Add receiving message components function to ESP32 program (BEFORE case statement... put data as ONE string)
- [ ] Flesh out ESP32 opcode functions (?)

**Comment by bgoodwine** [comment]
### Protocol Draft 2
Pi initial messages: 
* `0:` - general checking request 
* `1:sensor_id` - restart sensor corresponding to `sensor_id`
* `2:sensor_id` - shutdown sensor corresponding to `sensor_id`
* `3:[num_bytes]` - misc. message from Pi to ESP32

Pi responses to message transmission requests: 
* `0:2` - start relay of message to be sent to SDR (after receiving `0:2:[num_bytes]` from ESP32)
* `0:3` - start relay of solar panel efficiency report (sent after receiving `0:3:[num_bytes]` from ESP32)
* `0:4` - start relay of misc. message from ESP32 (sent after receiving `0:4:[num_bytes]` from ESP32)
 
ESP32 response to general checkin: 
* `0:0` - not tumbling
* `0:1` - tumbling alert
* `0:2:[num_bytes]` - a message of `num_bytes` bytes is waiting to be relayed to the Pi for transmission through the SDR
* `0:3:[num_bytes]` - solar panel efficiency report of `num_bytes` bytes is waiting to be relayed to the Pi 
* `0:4:[num_bytes]` - misc. message available for relay from ESP32 to Pi 

ESP32 response to restart/shutdown commands: 
* `1:0:[sensor_id]` - successfully restarted sensor of `sensor_id`
* `1:1:[sensor_id]` - failed to restart sensor of `sensor_id`
* `2:0:[sensor_id]` - successfully shutdown sensor of `sensor_id`
* `2:1:[sensor_id]` - failed to shutdown sensor of `sensor_id`

ESP32 data relay messages will be repeated until all bytes have been transmitted: 
* `0:2:[message]` - packetized data for transmission through SDR
* `0:3:[message]` - solar panel efficiency report 
* `0:4:[message]` - misc. message from ESP32 to Pi 
Note: the preceding opcode and delimiter will be included in the `num_bytes` originally sent.

**Comment by bgoodwine** [comment]
### Send I2C data back from ESP32 S3
[Read byte at a time with smbus](https://buildmedia.readthedocs.org/media/pdf/smbus2/latest/smbus2.pdf)
```
read_byte(i2c_addr, force=None)
Read a single byte from a device.
Return type int
Parameters
• i2c_addr (int) – i2c address
• force (Boolean) –
Returns Read byte value
```

[uint8 data type in python](https://stackoverflow.com/questions/33943075/u8-u16-u32-representation-in-python)
[read block data](https://www.kernel.org/doc/html/next/driver-api/i2c.html#c.i2c_smbus_read_block_data)

**Comment by bgoodwine** [comment]
### TODO
Lots of functionality added with #13 closed :) What's still left:
* Make `checkin()` a request from function
* Have Pi call the get functions based off of response from checkin
* Send variable lengths messages !
