### ISSUE TITLE
Integrate w/ tumbling

### ISSUE THREAD

**Issue by bgoodwine** [bgoodwine/SeniorDesign#6]
Tumbling detection subsystem code [repo](https://github.com/ndirishsat/SeniorDesign2023)
* Change `Serial.begin(9600);` speed
* See which I2C port the `Adafruit_BNO055 bno = Adafruit_BNO055(55);` line uses
* Remove `delay(1000);` & make the tumbling detection an ISR called every 1000ms (?)
* Look into RTOS tasks for this...?

**Comment by bgoodwine** [comment]
[Timer interrupts](https://circuitdigest.com/microcontroller-projects/esp32-timers-and-timer-interrupts)
```c++
hw_timer_t *My_timer = NULL;

void IRAM_ATTR onTimer(){
    digitalWrite(LED, !digitalRead(LED));
}

void setup() {
    pinMode(LED, OUTPUT);

    // timer number, prescaler, count up boolean
    My_timer = timerBegin(0, 80, true);
    timerAttachInterrupt(My_timer, &onTimer, true);

    // timer, wait time (1000000ms = 1s), reload boolean (run multiple times)
    timerAlarmWrite(My_timer, 1000000, true);
    timerAlarmEnable(My_timer);
}

**Comment by bgoodwine** [comment]
```c++
// #define TUMBLING_DELAY 1e+6!!!
#define TUMBLING_TMR 80
hw_timer_t *tmr = NULL;

void IRAM_ATTR on_timer(){
    // tumbling detection loop code
}

void setup() {
    // append to end of setup 
    My_timer = timerBegin(0, TUMBLING_TMR, true);
    timerAttachInterrupt(tmr, &on_timer, true);

    // timer, original loop delay time, reload = true
    timerAlarmWrite(tmr, TUMBLING_DELAY, true);
    timerAlarmEnable(tmr);
}
```

**Comment by bgoodwine** [comment]
Hardcoded the photoresistor & battery level variables, will have to undo that when connecting to the real breadboard!!

**Comment by bgoodwine** [comment]
### Add fuel gauge (MAX17048)
[Tutorial](https://learn.adafruit.com/adafruit-max17048-lipoly-liion-fuel-gauge-and-battery-monitor/arduino)
[Library](https://github.com/adafruit/Adafruit_BNO055/blob/master/Adafruit_BNO055.cpp)

**Comment by bgoodwine** [comment]
### TODO
- [x] Replace battery level code with fuel gauge readings
- [x] Add in the rest of the analog voltage power line readings & convert to volts
- [x] Switch MOSFET control of LEDs to PR/IMU/Pi/SDR
- [x] Update I2C device IDs to control new devices
- [x] Day cycle photoresistor - cover with hand = "dark", uncover = "light"
- [x] Send messages from tumbling detection to Pi instead of printing
- [x] Fix message beginning index issue
- [ ] Power ESP32 & Pi from power breadboard

### Check POWER
- [x] IMU - voltage range from datasheet that's acceptable 
- [x] Pi - try powering through the pins and get the voltage range from the datasheet 
- [x] SDR - write voltage range code but don't try to connect it

**Comment by bgoodwine** [comment]
If you hold en and boot and then release en, it *should* open the ROM bootloader, even with an entirely missing flash chip, so it should work fine with a corrupt firmware image.

But it not showing up in ports is troubling. Have you tried rebooting your computer?

https://www.reddit.com/r/esp32/comments/tjopez/bricked_esp32/

PLUS

Release GPIO0 from GND, otherwise stuck in bootloader waiting for next download
then cycle EN
https://github.com/mu-editor/mu/issues/2313

**Comment by bgoodwine** [comment]
### Status
Reading in the voltages from the voltage divider and calculating the voltages on the power lines
Detecting anomalies based off of the datasheet voltage range operation values
Added on/off control of the power lines via I2C command from the Pi
Fixed the dayCycleCheck function so the light/dark return works for the ESP's version of analog input
Tested the end to end 

However, currently not powering
